routes/web.php
<?php

use App\Mail\NewUserNotification;
use App\MainCategory;
use App\SubCategory;
use App\User;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;

$prefix = 'FrontendController\\';

Route::group(['prefix' => '/', 'as' => 'frontend.'], function () use ($prefix) {
    Route::get('/', $prefix . 'FrontendController@index')->name('index');
    Route::get('/signup', $prefix . 'FrontendController@signup')->name('signup');
    Route::get('/about-as', $prefix . 'FrontendController@AboutAs')->name('about-as');
    Route::get('/privacy', $prefix . 'FrontendController@Privacy')->name('privacy');
});

Route::group(['prefix' => '/services', 'as' => 'services.'], function () use ($prefix) {
    Route::get('/', $prefix . 'ServicesController@index')->name('index');
    Route::get('/create', $prefix . 'ServicesController@create')->name('create');
    Route::post('/store', $prefix . 'ServicesController@store')->name('store');
    Route::get('/show/{slug}', $prefix . 'ServicesController@show')->name('show');
    Route::get('/review/{slug}', $prefix . 'ServicesController@review')->name('review');
    Route::post('/set-offer', $prefix . 'ServicesController@setOffer')->name('set_offer');
    Route::post('/destroy/{id}', $prefix . 'ServicesController@destroy')->name('destroy');
    Route::post('/add-to-saved', $prefix . 'ServicesController@addToSaved')->name('addToSaved');
    Route::post('/block/{id}', $prefix . 'ServicesController@blockService')->name('block');
});

Route::group(['prefix' => '/ads', 'as' => 'ad.'], function () use ($prefix) {
    Route::get('/create', $prefix . 'AdsController@createAd')->name('create');
    Route::post('/generate-template', $prefix . 'AdsController@generateTemplate')->name('template');
    Route::post('/store', $prefix . 'AdsController@store')->name('store');
    Route::get('/', $prefix . 'AdsController@showAds')->name('show-ads');
    Route::get('/category/{id}', $prefix . 'AdsController@getAdsWhereCategory')->name('category');
    Route::get('/show/{id}', $prefix . 'AdsController@showAd')->name('show-ad');
    Route::post('/add-to-saved', $prefix . 'AdsController@addToSaved')->name('addToSaved');
    Route::post('/set-auction-offer', $prefix . 'AdsController@setAuctionOffer')->name('set-auction-offer');
    Route::post('/set-comment', $prefix . 'AdsController@setComment')->name('set-comment');
    Route::post('/block/{id}', $prefix . 'AdsController@blockAd')->name('block');
    Route::get('/delete-comment/{id}', $prefix . 'AdsController@deleteComment')->name('delete-comment');
});

Route::group(['prefix' => '/users', 'as' => 'users.'], function () use ($prefix) {
    Route::get('/profile/{username}', $prefix . 'UsersController@profile')->name('profile');
    Route::get('/saved', $prefix . 'UsersController@saved')->name('saved');
    Route::post('/update', $prefix . 'UsersController@update')->name('update');
    Route::post('/change-password', $prefix . 'UsersController@changePassword')->name('change-password');
    Route::post('/follow-user', $prefix . 'UsersController@followUser')->name('follow-user');
    Route::post('/user-block/{id}', $prefix . 'UsersController@userBlock')->name('block');
    Route::get('/all', $prefix . 'UsersController@allUsers')->name('all');
});

Route::group(['prefix' => '/auctions', 'as' => 'auctions.'], function () use ($prefix) {
    Route::get('/', $prefix . 'AuctionsController@index')->name('index');
});

Route::group(['prefix' => '/general', 'as' => 'general.'], function () use ($prefix) {
    Route::post('/store-message', $prefix . 'GeneralController@storeMessage')->name('store-message');
    Route::post('/store-report-ad', $prefix . 'GeneralController@storeReportAd')->name('store-report-ad');
    Route::post('/store-rating', $prefix . 'GeneralController@storeRating')->name('store-rating');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('test', 'TestController');
Route::post('/api/sub_categories', 'Api\\CategoriesController@selectSubCategorie')->name('api.sub_categories');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/foo', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('storage:link');
    // Artisan::call('voyager:install');
    return "<h1> OK :) </h1>";
});

Route::get('/tmail', function () {
    $user = User::find(18);
    Mail::to($user)->send(new NewUserNotification($user));
});

app/Http/Controllers/FrontendController/FrontendController.php
<?php

namespace App\Http\Controllers\FrontendController;

use App\Http\Controllers\Controller;
use App\MainCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FrontendController extends Controller
{
    public function index()
    {
        $categories = MainCategory::with('sub_categories')->get();
        return view('frontend.pages.index', compact('categories'));
    }

    public function signup()
    {
        if (!Auth::check()) {
            return view('frontend.pages.signup');
        }
        else{
            return redirect()->to('/');
        }
    }

    public function AboutAs()
    {
        return view('frontend.pages.about-as');
    }

    public function Privacy()
    {
        return view('frontend.pages.privacy');
    }
}

resources/views/frontend/includes/articles.blade.php
<section class="articles">
    <div class="container">
        <h2>مقالات كورسات</h2>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title color-pink">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>أسئلة برمجية</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2> ماهو الفرق بين nodejs و angualrjs</h2>
                        <p>كيفية اتمام تنصيب ووردبريس وتركيبه وتنسيقه واعداده من البداية مع مجموعة مهارات اضافيةمن
                            البداية مع مجموعة مهارات اضافية</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>مقالات عامة</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2>ايهما أفضل التخزين الوقت في القواعد</h2>
                        <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد أن تولد
                            مثل هذا النص أو العديد من النصوص</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title color-green">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>لقائات برمجية</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2>ايهما أفضل التخزين الوقت في القواعد</h2>
                        <p>هذا النص هو دل في نفس المساحة، لقد تم توليد هذا النص من أو العديد من النصوص</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>أسئلة برمجية</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2>مجموعة تصاميم ومخطوطات</h2>
                        <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد أن تولد
                            مثل هذا النص أو العديد من النصوص</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title color-green">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>أسئلة برمجية</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2>لكل من يعشق عالم الهواتف</h2>
                        <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد أن تولد
                            مثل هذا النص أو العديد من النصوص</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
            <div class="box-article">
                <div class="col-lg-2 col-md-4 col-sm-4 col-xs-4 box-article img-none">
                    <a href="articles.html">
                        <div class="section-title">
                            <img src="{{ asset('assets/images/articels-img.jpg') }}">
                            <span>أسئلة برمجية</span>
                        </div>
                    </a>
                </div>
                <div class="col-lg-8 col-lg-offset-2 col-md-8 col-sm-8 col-xs-12 box-article">
                    <a href="articles.html">
                        <h2>ايهما أفضل التخزين الوقت في القواعد</h2>
                        <p>هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد أن تولد
                            مثل هذا النص أو العديد من النصوص</p>
                    </a>
                    <div class="article-comments">
                        <span>29<img src="{{ asset('assets/images/comment.jpg') }}"></span>
                        <span>2<img src="{{ asset('assets/images/like.jpg') }}"></span>
                        <span>FEB 12,2015<img src="{{ asset('assets/images/share.jpg') }}"></span>
                    </div>
                </div>
            </div>
        </div>
        <a href="articles.html"><button type="submit">عرض المزيد من المقالات</button></a>
    </div>
</section>

resources/views/frontend/includes/categories-list.blade.php
<div class="articles-color-white">
    <h2>التصنيفات</h2>
    @foreach ($categories as $main_cat)        
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" href="#category{{$main_cat->id}}">
                            {{ $main_cat->name }}
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                        </a>
                    </h4>
                </div>
                <div id="category{{$main_cat->id}}" class="panel-collapse collapse">
                    @foreach ($main_cat->sub_categories as $sub_cat)
                        <div class="panel-body">
                            <a href="{{ $link .'?category='.$sub_cat->id }}">{{ $sub_cat->name }}</a> 
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    @endforeach
</div>

resources/views/frontend/includes/filter.blade.php
@push('scripts')
    @include('frontend.scripts.ajax_select' , [ 
        'perant' => 'main_category_id', 
        'child' => 'sub_category_id',
        'route' => 'api.sub_categories' 
    ])
@endpush
<div class="row">
    <div class="col-md-12">
        @include('frontend.forms.select' , [
            'name' => 'main_category_id',
            'label' => 'القسم الرئيسي',
            'required' => false,
            'options' => Helper::getMainCategories(),
            'col' => 12
        ])
    </div>
    <div class="col-md-12">
        @include('frontend.forms.select' , [
            'name' => 'sub_category_id',
            'label' => 'القسم الفرعي',
            'required' => false,
            'options' => [],
            'col' => 12
        ])
    </div>
    <div class="col-md-12">
        @include('frontend.forms.select' , [
            'name' => 'city_id',
            'label' => 'المدينة',
            'required' => false,
            'options' => Helper::getCities(),
            'col' => 12
        ])
    </div>
    <div class="col-md-12">
        <div class="form-group col-sm-12 col-md-12">
            <button class="btn btn-red btn-block">بحث</button>
        </div>
    </div>
</div>

resources/views/frontend/includes/filter_header.blade.php
<header class="header-inside" style="background-image: url('{{ asset('assets/images/cover3.jpg') }}')">
    <div class="container">
        <div class="body-header-inside">
            <form  action="{{ route('ad.show-ads') }}" method="GET">
                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-8 bg-filter">
                    <div class="form-group col-sm-12 col-md-6">
                        <label class="text-right" for="main_category_id"> 
                            القسم الرئيسي:
                        </label>
                        <select class="e-form-control" id="main_category_id" name="main_category_id">
                            <option value="">-- اختر --</option>
                            @foreach(Helper::getMainCategories() as $key => $value)
                                <option value="{{ $key }}">{{ $value }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group col-sm-12 col-md-6">
                        <label class="text-right" for="sub_category_id"> 
                            القسم الفرعي:
                        </label>
                        <select class="e-form-control" id="sub_category_id" name="sub_category_id">
                            <option value="">-- اختر --</option>
                        </select>
                    </div>

                    <div class="form-group col-sm-12 col-md-12">
                        <label class="text-right" for=""> 
                            ابحث: 
                        </label>
                        <div class="input-group">

                            <input type="text" class="e-form-control" name="s" placeholder="ابحث عن اي شيء ...">
                            <div class="input-group-btn">
                                <button class="btn btn-red" type="submit">
                                    <i class="fa fa-search" aria-hidden="true"></i>
                                    بحث
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                    <div class="col-md-2"></div>

                </div>
            </form>
        </div>
    </div>
</header>

resources/views/frontend/includes/footer.blade.php
<section class="footer-section text-center">
    <ul>
        <li><a href="/">الرئيسية </a></li>
        <li><a href="{{ route('frontend.about-as') }}">من نحن</a></li>
        <li><a href="{{ route('frontend.privacy') }}">شروط الاستخدام</a></li> 
        <img src="{{ asset('images/logo2.png') }}" width="90px">
        <li><a href="{{ route('services.index') }}">الخدمات</a></li>
        <li><a href="{{ route('ad.show-ads') }}">اخر الاعلانات</a></li>
        <li><a href="{{ route('frontend.signup') }}">حساب جديد</a></li>
    </ul>
    <p>جميع الحقوق محفوظة لموقع كراكيب فلسطين 2020</p>
    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
</section>

resources/views/frontend/includes/header.blade.php
<header class="header-inside">
    <div class="container">
        <div class="row">
        <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
            <div class="body-header-inside">
                <div class="display-center">
                    <img src="{{ asset($image ?? '') }}" height="160px">
                    <div class="header-text">
                        <h2>{{ $title }}</h2>
                        <p>{{ $desc }}</p>
                        @if (isset($link))
                            <a href="{{$link}}" class="btn btn-default">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                {{$textLink ?? ''}}
                            </a>
                        @endif
                    </div>
                </div>
                {{-- <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
                </div> --}}
            </div>
        </div>

        {{-- <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 text-center display-center">
        </div> --}}
    </div>
    </div>
</header>

resources/views/frontend/includes/model.blade.php
<style>
    #fixedbutton {
        position: fixed;
        bottom: 0px;
        left: 50px; 
        border-radius: 10px 10px 0px 0px !important;
        padding: 6px 16px !important;
        font-weight: normal;
    }
    .modal-title{
        font-weight: bold;
    }

</style>
@include('frontend.components.validation')
<!-- Button trigger modal -->
<button type="button" id="fixedbutton" class="btn btn-red" data-toggle="modal" data-target="#exampleModal">
    <i class="fa fa-envelope-o" aria-hidden="true"></i>
    أرسل ملاحظاتك
  </button>
  
  <!-- Modal -->
  <div class="modal font-kufi fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header text-center">
          <h4 class="modal-title i-color-red font-kufi" id="exampleModalLabel">
              أرسل ملاحظاتك
          </h4>
          {{-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button> --}}
        </div>
        <div class="modal-body">
            <div class="container-fluid">
                <div class="row">
                    <form action="{{ route('general.store-message') }}" method="POST" id="form_message">
                        @csrf
                        @include('frontend.forms.select' , [
                            'name' => 'type',
                            'label' => 'نوع الملاحظة',
                            'required' => false,
                            'options' => Helper::getTypeMessage(),
                            'col' => 12
                        ])
                        @include('frontend.forms.input' , [
                            'name' => 'email',
                            'label' => 'البريد الالكتروني',
                            'placeholder' => 'أدخل البريد الالكتروني',
                            'type' => 'text',
                            'required' => false,
                            'col' => 12,
                            'value' => Auth::check() ? Auth::user()->email : ''
                        ])
                        @include('frontend.forms.textarea' , [
                            'name' => 'body',
                            'label' => 'الرسالة',
                            'placeholder' => 'ادخل نص الرسالة',
                            'required' => false,
                            'col' => 12
                        ])
                    </form>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">إغلاق</button>
          <button type="submit" form="form_message" class="btn btn-red">إرسال</button>
        </div>
      </div>
    </div>
  </div>

resources/views/frontend/includes/navbar.blade.php
<div class="nav_bar">
    <nav class="navbar  navbar-icon-top navbar-default">
        <div class="container">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                    
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    {{-- <h2>كراركيب</h2> --}}
                    {{-- <img src="{{ asset('images/logo.png') }}" width="110"> --}}
                    <a class="navbar-brand" rel="home" href="/" title="Buy Sell Rent Everyting">
                        <img style="max-width:110px; margin-top: -11px;"
                             src="{{ asset('images/logo.png') }}">
                    </a>
                </div>
           
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>

                            <a href="{{ route('frontend.index') }}">
                                <i class="fa fa-home"></i>
                                الرئيسية 
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('frontend.about-as') }}">
                                <i class="fa fa-info"></i>
                                من نحن
                            </a>
                        </li>
                        
                        <li>
                            <a href="{{ route('users.all') }}">
                                <i class="fa fa-users"></i>
                                الاعضاء
                            </a>
                        </li>
                        
                        <li>
                            <a href="{{ route('services.index') }}">
                                <i class="fa fa-archive" aria-hidden="true"></i>
                                طلب خدمة                            
                            </a>
                        </li>
                        
                        <li>
                            <a href="{{ route('ad.show-ads') }}">
                                <i class="fa fa-paper-plane" aria-hidden="true"></i>
                                اخر الاعلانات                            
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('auctions.index') }}">
                                <i class="fa fa-line-chart " aria-hidden="true"></i>
                                المزاد                            
                            </a>
                        </li>
                        <li>
                            <a href="{{ route('users.saved') }}">
                                <i class="fa fa-bookmark" aria-hidden="true"></i>
                                المحفوظات
                            </a>
                        </li>
                        {{-- <li class="dropdown">
                            <a href="sections.html" class="dropbtn">الأقسام<span class="caret"></span></a>
                            <ul class="dropdown-content text-right">
                                <li><a href="inside-section.html">قسم التصميم</a></li>
                                <li><a href="inside-section.html">قسم البرمجة</a></li>
                                <li><a href="inside-section.html">قسم التسويق</a></li>
                                <li><a href="inside-section.html">قسم الرياضيات</a></li>
                            </ul>
                        </li>
                        <li><a href="articles.html">المقالات</a></li> --}}
                        @include('frontend.components.login-model')
                        <li>
                            <a href="{{ route('ad.create') }}" class="active">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                                أضف إعلان مجاناً
                            </a>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </div>
    </nav>
</div>

resources/views/frontend/includes/social-link.blade.php
<div class="articles-color-white">
    <div class="follow-us">
        <h2>تابعنا</h2>
        <div class="social-media">
            <div class="color-facebook"><a href="#"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
            </div>
            <div class="color-twitter"> <a href="#"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
            </div>
            <div class="color-instagram"><a href="#"><i class="fa fa-instagram fa-2x"
                        aria-hidden="true"></i></a></div>
            <div class="color-behance"><a href="#"><i class="fa fa-behance fa-2x" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/includes/top-categories.blade.php
    <div class="col-md-3 text-center">
        <a href="{{ route('ad.show-ads' , ['main_category_id' => $category->id]) }}">
            <div class="cat-card">
                <img src="{{url('storage/' . $category->icon)}}" height="50px" alt="">
                <p>{{$category->name}}</p>
                <span style="font-size: 12px">اعلان: {{$category->ads->count()}}</span>
            </div>
        </a>
    </div>