routes/web.php
<?php

use App\Mail\NewUserNotification;
use App\MainCategory;
use App\SubCategory;
use App\User;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;

$prefix = 'FrontendController\\';

Route::group(['prefix' => '/', 'as' => 'frontend.'], function () use ($prefix) {
    Route::get('/', $prefix . 'FrontendController@index')->name('index');
    Route::get('/signup', $prefix . 'FrontendController@signup')->name('signup');
    Route::get('/about-as', $prefix . 'FrontendController@AboutAs')->name('about-as');
    Route::get('/privacy', $prefix . 'FrontendController@Privacy')->name('privacy');
});

Route::group(['prefix' => '/services', 'as' => 'services.'], function () use ($prefix) {
    Route::get('/', $prefix . 'ServicesController@index')->name('index');
    Route::get('/create', $prefix . 'ServicesController@create')->name('create');
    Route::post('/store', $prefix . 'ServicesController@store')->name('store');
    Route::get('/show/{slug}', $prefix . 'ServicesController@show')->name('show');
    Route::get('/review/{slug}', $prefix . 'ServicesController@review')->name('review');
    Route::post('/set-offer', $prefix . 'ServicesController@setOffer')->name('set_offer');
    Route::post('/destroy/{id}', $prefix . 'ServicesController@destroy')->name('destroy');
    Route::post('/add-to-saved', $prefix . 'ServicesController@addToSaved')->name('addToSaved');
    Route::post('/block/{id}', $prefix . 'ServicesController@blockService')->name('block');
});

Route::group(['prefix' => '/ads', 'as' => 'ad.'], function () use ($prefix) {
    Route::get('/create', $prefix . 'AdsController@createAd')->name('create');
    Route::post('/generate-template', $prefix . 'AdsController@generateTemplate')->name('template');
    Route::post('/store', $prefix . 'AdsController@store')->name('store');
    Route::get('/', $prefix . 'AdsController@showAds')->name('show-ads');
    Route::get('/category/{id}', $prefix . 'AdsController@getAdsWhereCategory')->name('category');
    Route::get('/show/{id}', $prefix . 'AdsController@showAd')->name('show-ad');
    Route::post('/add-to-saved', $prefix . 'AdsController@addToSaved')->name('addToSaved');
    Route::post('/set-auction-offer', $prefix . 'AdsController@setAuctionOffer')->name('set-auction-offer');
    Route::post('/set-comment', $prefix . 'AdsController@setComment')->name('set-comment');
    Route::post('/block/{id}', $prefix . 'AdsController@blockAd')->name('block');
    Route::get('/delete-comment/{id}', $prefix . 'AdsController@deleteComment')->name('delete-comment');
});

Route::group(['prefix' => '/users', 'as' => 'users.'], function () use ($prefix) {
    Route::get('/profile/{username}', $prefix . 'UsersController@profile')->name('profile');
    Route::get('/saved', $prefix . 'UsersController@saved')->name('saved');
    Route::post('/update', $prefix . 'UsersController@update')->name('update');
    Route::post('/change-password', $prefix . 'UsersController@changePassword')->name('change-password');
    Route::post('/follow-user', $prefix . 'UsersController@followUser')->name('follow-user');
    Route::post('/user-block/{id}', $prefix . 'UsersController@userBlock')->name('block');
    Route::get('/all', $prefix . 'UsersController@allUsers')->name('all');
});

Route::group(['prefix' => '/auctions', 'as' => 'auctions.'], function () use ($prefix) {
    Route::get('/', $prefix . 'AuctionsController@index')->name('index');
});

Route::group(['prefix' => '/general', 'as' => 'general.'], function () use ($prefix) {
    Route::post('/store-message', $prefix . 'GeneralController@storeMessage')->name('store-message');
    Route::post('/store-report-ad', $prefix . 'GeneralController@storeReportAd')->name('store-report-ad');
    Route::post('/store-rating', $prefix . 'GeneralController@storeRating')->name('store-rating');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('test', 'TestController');
Route::post('/api/sub_categories', 'Api\\CategoriesController@selectSubCategorie')->name('api.sub_categories');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/foo', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('storage:link');
    // Artisan::call('voyager:install');
    return "<h1> OK :) </h1>";
});

Route::get('/tmail', function () {
    $user = User::find(18);
    Mail::to($user)->send(new NewUserNotification($user));
});

app/Service.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Service extends Model
{

    protected $fillable = [
        'title',
        'description',
        'budget_min',
        'budget_max',
        'city_id',
        'sub_category_id',
        'currency_id'
    ];
    protected $appends = ['saved'];
    protected static function boot()
    {
        parent::boot();

        static::creating(function ($question) {
            $temp = preg_replace('~[^\pL\d]+~u', '-', $question->title);;
            if (!Service::all()->where('slug', $temp)->isEmpty()) {
                $i = 1;
                $new_slug = $temp . '-' . $i;
                while (!Service::all()->where('slug', $new_slug)->isEmpty()) {
                    $i++;
                    $new_slug = $temp . '-' . $i;
                }
                $temp = $new_slug;
            }
            $question->slug = $temp;
            $question->user_id = Auth::id();
        });
    }

    public function sub_category()
    {
        return $this->belongsTo(SubCategory::class,  'sub_category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function city()
    {
        return $this->belongsTo(City::class, 'city_id');
    }

    public function currency()
    {
        return $this->belongsTo(Currency::class, 'currency_id');
    }

    public function offers()
    {
        return $this->hasMany(Offer::class)->with('user');
    }


    public function scopeFindBySlug($query, $slug)
    {
        return $query->where('slug', '=', $slug);
    }

    public function scopeWhereStatus($query, $status)
    {
        return $query->where('status', '=', $status);
    }

    public function getSavedAttribute()
    {
        if (!Auth::check()) {
            return 0;
        } else {
            $saved_service = SavedService::where('user_id', Auth::id())
                ->where('service_id', $this->id)->first();
            return ($saved_service) ? 1 : 0;    
        }
    }

    public function scopeServiceUser($query)
    {
        if (Auth::user()->role->name == 'user') {
            return $query->where('user_id', '=', Auth::id());
        }
    }
}

app/Http/Controllers/FrontendController/ServicesController.php
<?php

namespace App\Http\Controllers\FrontendController;

use App\Http\Controllers\Controller;
use App\Mail\ServiceAcceptNotification;
use App\MainCategory;
use App\Offer;
use App\Providers\Helper;
use App\SavedService;
use App\Service;
use App\SubCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class ServicesController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->only(['create', 'store']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $services = Service::select('*')->where('status', Helper::ACTIVE);
        if ($request->main_category_id != null) {
            $services = MainCategory::find($request->main_category_id)->services()->where('status', Helper::ACTIVE);
        }
        if ($request->sub_category_id != null) {
            $services->where('sub_category_id', '=', $request->sub_category_id);
        }
        if ($request->city_id != null) {
            $services->where('city_id', '=', $request->city_id);
        }
        if (!isset($request->order_by) or $request->order_by == null) {
            $services->orderBy('created_at', 'DESC');
        }

        if ($request->order_by != null) {
            $services->orderBy('created_at', $request->order_by);
        }

        $data  =  $services->paginate(7)->setPath('')->appends($request->all());
        return view('frontend.pages.services.index', ['services' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('frontend.pages.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $this->validate($request, $this->rule(), [], $this->niceNames());
        $service = Service::create($request->all());
        return redirect()->route('services.review', [$service->slug]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $service =  Service::findBySlug($slug)->with('offers')->first();
        if ($service) {
            if ($service->status == Helper::ACTIVE) {
                return view('frontend.pages.services.show', compact('service'));
            } else {
                return redirect()->route('services.review', [$slug]);
            }
        }
        return view('frontend.pages.404');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $service = Auth::user()->services()->findOrFail($id);
        $service->delete();
        return redirect()->back()->with('success', 'تم الحذف بنجاح');
    }

    public function setOffer(Request $request)
    {
        $validatedData = $this->validate($request, $this->ruleOffer(), [], $this->niceNamesOffer());
        $offer = Offer::create($request->all());
        return redirect()->back()->with('success', 'تم التعليق بنجاح');
    }

    public function review($slug)
    {
        $service =  Service::findBySlug($slug)->first();
        if ($service) {
            if ($service->status == Helper::DEACTIVE) {
                return view('frontend.pages.review');
            } else {
                return view('frontend.pages.services.show', compact('service'));
            }
        }
        return view('frontend.pages.404');
    }

    public function rule()
    {
        return [
            'sub_category_id' => 'required|integer|exists:sub_categories,id',
            'city_id' => 'required|integer|exists:cities,id',
            'title' => 'required|max:255',
            'description' => 'required|max:3000',
            'budget_min' => 'required|integer|min:0',
            'budget_max' => 'required_with|integer|gte:budget_min|min:0',
        ];
    }

    public function niceNames()
    {
        return [
            'sub_category_id' => __('fillable.sub_category_id'),
            'city_id' => __('fillable.city_id'),
            'title' => __('fillable.title'),
            'description' => __('fillable.description'),
            'budget_min' => __('fillable.budget_min'),
            'budget_max' => __('fillable.budget_max'),
        ];
    }


    public function addToSaved(Request $request)
    {
        if (isset($request->service_id) and Auth::check()) {
            $saved_service = SavedService::where('user_id', Auth::id())
                ->where('service_id', $request->service_id)->first();
            if ($saved_service) {
                $saved_service->delete();
                return response()->json([
                    'success' => true,
                    'message' => 'تم الازالة من قائمة المحفوظات',
                    'action' => 'unsaved'
                ]);
            } else {
                SavedService::insert([
                    'service_id' => $request->service_id,
                    'user_id' => Auth::id()
                ]);
                return response()->json([
                    'success' => true,
                    'message' => "تم الاضافة الى قائمة المحفوظات",
                    'action' => 'saved'
                ]);
            }
        }
        return response()->json([
            'success' => false,
            'message' => "يجب تسجيل الدخول اولا"
        ]);
    }

    public function ruleOffer()
    {
        return [
            'service_id' => 'required|integer|min:0',
            'amount' => 'required|integer',
            'body' => 'required|max:1000',
            'currency_id' => 'required|integer|min:0',
        ];
    }

    public function niceNamesOffer()
    {
        return [
            'service_id' => __('fillable.service_id'),
            'amount' => __('fillable.amount'),
            'body' => __('fillable.body'),
            'currency_id' => __('fillable.currency_id'),
        ];
    }

    public function blockService($id)
    {
        $service = Service::findOrFail($id);
        $service->status = ($service->status == Helper::ACTIVE) ?  Helper::DEACTIVE : Helper::ACTIVE;
        $service->save() ;
        if($service->status == Helper::ACTIVE){
            Mail::to($service->user)->send(new ServiceAcceptNotification($service));
            return redirect()->back()->with([
                'message'    => 'The request was successfully accepted',
                'alert-type' => 'success',
            ]);
        }
        return redirect()->back()->with([
            'message'    => 'The block was successful',
            'alert-type' => 'success',
        ]);
    }
}

resources/views/frontend/pages/services/create.blade.php
@extends('frontend.layouts.master')

@push('title')
اطلب خدمة
@endpush

@push('scripts')
    @include('frontend.scripts.ajax_select' , [ 
        'perant' => 'main_category_id', 
        'child' => 'sub_category_id',
        'route' => 'api.sub_categories' 
    ])
@endpush

@section('content')

<div class="container-fluid color-gray">
    <div class="container">
        <div class="row">
            <br><br>
            <div class="col-sm-12 col-md-8">
                <div class="e-panel panel-black">
                    <div class="e-panel-heading">اطلب خدمة او منتج مجاناً</div>
                    <div class="panel-body">
                        @include('frontend.components.validation')
                        <form  action="{{ route('services.store') }}" method="POST">
                            @csrf
                            @include('frontend.forms.service')
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-sm-12 col-md-4">
                <h3 class="font-kufi font-bold">ابدأ ببناء مشروعك</h3> 
                <p class="font-naskh font-size-17 text-justify">
                    من خلال مستقل تستطيع بناء مشروعك بالشكل الذي تريد، أدخل تفاصيل المشروع والميزانية المتوقعة، ليتم مراجعة مشروعك ونشره مجاناً على مستقل.
بعد ذلك، سيتقدّم أفضل المستقلين المسجلين بعروض مختلفة لتختار العرض المناسب لك وتبدأ بتنفيذ مشروعك.
                </p>
                <h3 class="font-kufi font-bold">ابدأ ببناء مشروعك</h3> 
                <p class="font-naskh font-size-17 text-justify">
                    من خلال مستقل تستطيع بناء مشروعك بالشكل الذي تريد، أدخل تفاصيل المشروع والميزانية المتوقعة، ليتم مراجعة مشروعك ونشره مجاناً على مستقل.
بعد ذلك، سيتقدّم أفضل المستقلين المسجلين بعروض مختلفة لتختار العرض المناسب لك وتبدأ بتنفيذ مشروعك.
                </p>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/frontend/pages/services/index.blade.php
@extends('frontend.layouts.master')

@push('title')
    اطلب خدمة
@endpush

@section('content')
<section class="color-gray">
    <div class="container">
        <div class="row">
            <h3 class="font-kufi font-bold">ابدأ ببناء مشروعك</h3> 
            <p class="font-naskh font-size-17 text-justify">
                من خلال مستقل تستطيع بناء مشروعك بالشكل الذي تريد، أدخل تفاصيل المشروع والميزانية المتوقعة، ليتم مراجعة مشروعك ونشره مجاناً على مستقل.شروعك. 
            </p>
        </div>
        <br>
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="row">
                    <div class="col-md-12">
                        <div class="head-filter color-fff">
                        <div class="row">
                                <div class="col-md-6">                            
                                    <div class="order-by">
                                        <span>فرز حسب:</span>
                                        <select form="filterForm" name="order_by" id="order_by" class="e-form-control" style="width: 40%;"  onchange="this.form.submit()">
                                            <option value="DESC" @if (Request::get('order_by') == 'DESC') selected @endif>الأحث</option>
                                            <option value="ASC" @if (Request::get('order_by') == 'ASC') selected @endif>الأقدم</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <a href="{{ route('services.create') }}" class="btn btn-red pull-left">
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                        أضف طلبك
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="e-panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            @if ($services->count() == 0)
                                <div class="col-md-12 text-center">
                                    <p> لا توجد نتائج 😉 </p>
                                    <a href="{{ route('services.create') }}" class="btn btn-red"> 
                                        <i class="fa fa-plus-circle" aria-hidden="true"></i> 
                                        قم باضافة طلبك
                                    </a>
                                </div>
                            @else
                                <div class="col-md-12">
                                    @include('frontend.components.service' , ['services' => $services , 'action' => false])
                                </div>
                            @endif
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-center">
                                {{ $services->links() }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <div class="e-panel panel-default">
                    <div class="e-panel-heading"> حدد التصنيف الخاص بك </div>
                    <div id="service-info" class="panel-collapse collapse collapse in">
                        <div class="panel-body">
                            <form id="filterForm" action="{{ route('services.index') }}" method="GET">
                                @include('frontend.includes.filter')
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {{-- <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <div class="row">
                    <div class="col-md-12">
                        <a href="{{ route('services.create') }}" class="btn btn-red btn-block">
                            <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            أضف طلبك
                        </a>
                    </div>
                </div>
                <br>
                <div class="left-articles"> 
                    @include('frontend.includes.categories-list' , ['categories' => $categories , 'link' => route('services.index')])

                    @include('frontend.includes.social-link')
                </div>
            </div> --}}

        </div>
    </div>
</section>
@endsection

resources/views/frontend/pages/services/offers.blade.php
<div class="e-panel panel-default">
    <div class="e-panel-heading">
        <a class="btn-collapse pull-left" data-toggle="collapse" href="#offers" aria-expanded="true">
            <i class="fa fa-angle-right"></i>
            <i class="fa fa-angle-down"></i>
        </a>
        عروض تم طرحها
    </div>
    <div id="offers" class="panel-collapse collapse collapse in">
        <div class="panel-body">
            <div class="row">
                @foreach ($offers as $offer)
                    
                <div class="col-md-12">
                    @include('frontend.components.offer' , compact('offer'))
                </div>
                <hr>
                @endforeach
            </div>
        </div>
    </div>
</div>

resources/views/frontend/pages/services/show.blade.php
@extends('frontend.layouts.master')

@push('title')
    اطلب خدمة
@endpush

@section('content')
    <section class="articles-section color-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
                    <div class="info-service">
                        <div class="e-panel panel-default">
                            <div class="e-panel-heading">
                                <a class="btn-collapse pull-left" data-toggle="collapse" href="#service-info" aria-expanded="true">
                                    <i class="fa fa-angle-right"></i>
                                    <i class="fa fa-angle-down"></i>
                                </a>
                                <h2> <span class="badge dark-green">مفتوح</span>{{ $service->title }}</h2>
                                <div class="s-icon pull-left">
                                    <div class="v-center"> 
                                        <i class="fa fa-clock-o i-color-green"></i>    
                                        <span>{{ $service->created_at->locale('ar')->diffForHumans() }}</span>
                                    </div>
                                </div>
                                <div class="s-icon">
                                    <div class="v-center"> 
                                        <i class="fa fa-user i-color-gold"></i> 
                                        <span>{{ $service->user->name }}</span>
                                    </div>
                                </div>
                    
                                <div class="s-icon">
                                    <div class="v-center"> 
                                        <i class="fa fa-map-marker i-color-pinck"></i> 
                                        <span>{{ $service->city->name }}</span>
                                    </div>
                                </div>
                    
                                <div class="s-icon">
                                    <div class="v-center"> 
                                        <i class="fa fa-list-alt i-color-blue"></i>
                                        <span> {{ $service->sub_category->name }}</span>
                                    </div>
                                </div>
                    
                                <div class="s-icon">
                                    <div class="v-center"> 
                                        <i class="fa fa-clock-o i-color-green"></i>    
                                        <span> {{ date('yy-m-d',strtotime($service->created_at)) }}</span>
                                    </div>
                                </div>
                            </div>
                            <div id="service-info" class="panel-collapse collapse collapse in">
                                <div class="panel-body">
                                    <div class="row">
                                        <div class="articles-body color-fff">
                                            <p>{!! nl2br($service->description) !!}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="offer">
                        @if ($errors->any())
                            @foreach ($errors->all() as $error)
                                @php
                                    toastr()->error($error);
                                @endphp
                            @endforeach
                        @endif
                        @if(Session::has('success'))
                            @php
                                toastr()->success(Session::get('success'));
                            @endphp
                        @endif
                        @include('frontend.forms.offer' , ['service_id' => $service->id])
                    </div>
                    
                    @guest
                    @else
                        @if (Auth::id() == $service->user_id)
                            <div class="offers">
                                @include('frontend.pages.services.offers' , ['offers' => $service->offers])
                            </div>
                        @endif
                    @endguest
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="articles-body color-fff">
                        <table class="table table-borderless" style="margin-bottom: 0px;">
                            <tbody>
                                <tr>
                                    <th style="width: 115px;">الميزانية:</th>
                                    <td> {{ $service->budget_min . ($service->currency->icon ?? '') }} - {{ $service->budget_max . ($service->currency->icon?? '') }} </td>
                                </tr>
                                <tr>
                                    <th style="width: 115px;">عدد العروض:</th>
                                    <td>{{ $service->offers->count() }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="articles-body color-fff">
                        <div class="user-info">
                            <img class="img-circle avatar img-thumbnail" height="70px"  width="70px" src="{{ url('storage/' . $service->user->avatar) }}">
                            <div class="info">
                                <h4>{{ $service->user->name }}</h4>
                                <p> <i class="fa fa-shield i-color-green" aria-hidden="true"></i> حساب موثق</p>
                                <p> <strong> تم الانضمام: </strong> {{ $service->user->created_at->locale('ar')->diffForHumans() }}</p>
                            </div>
                        </div>
                        <p class="text-center phone">{{ $service->user->phone ?? '' }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection