routes/web.php
<?php

use App\Mail\NewUserNotification;
use App\MainCategory;
use App\SubCategory;
use App\User;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;

$prefix = 'FrontendController\\';

Route::group(['prefix' => '/', 'as' => 'frontend.'], function () use ($prefix) {
    Route::get('/', $prefix . 'FrontendController@index')->name('index');
    Route::get('/signup', $prefix . 'FrontendController@signup')->name('signup');
    Route::get('/about-as', $prefix . 'FrontendController@AboutAs')->name('about-as');
    Route::get('/privacy', $prefix . 'FrontendController@Privacy')->name('privacy');
});

Route::group(['prefix' => '/services', 'as' => 'services.'], function () use ($prefix) {
    Route::get('/', $prefix . 'ServicesController@index')->name('index');
    Route::get('/create', $prefix . 'ServicesController@create')->name('create');
    Route::post('/store', $prefix . 'ServicesController@store')->name('store');
    Route::get('/show/{slug}', $prefix . 'ServicesController@show')->name('show');
    Route::get('/review/{slug}', $prefix . 'ServicesController@review')->name('review');
    Route::post('/set-offer', $prefix . 'ServicesController@setOffer')->name('set_offer');
    Route::post('/destroy/{id}', $prefix . 'ServicesController@destroy')->name('destroy');
    Route::post('/add-to-saved', $prefix . 'ServicesController@addToSaved')->name('addToSaved');
    Route::post('/block/{id}', $prefix . 'ServicesController@blockService')->name('block');
});

Route::group(['prefix' => '/ads', 'as' => 'ad.'], function () use ($prefix) {
    Route::get('/create', $prefix . 'AdsController@createAd')->name('create');
    Route::post('/generate-template', $prefix . 'AdsController@generateTemplate')->name('template');
    Route::post('/store', $prefix . 'AdsController@store')->name('store');
    Route::get('/', $prefix . 'AdsController@showAds')->name('show-ads');
    Route::get('/category/{id}', $prefix . 'AdsController@getAdsWhereCategory')->name('category');
    Route::get('/show/{id}', $prefix . 'AdsController@showAd')->name('show-ad');
    Route::post('/add-to-saved', $prefix . 'AdsController@addToSaved')->name('addToSaved');
    Route::post('/set-auction-offer', $prefix . 'AdsController@setAuctionOffer')->name('set-auction-offer');
    Route::post('/set-comment', $prefix . 'AdsController@setComment')->name('set-comment');
    Route::post('/block/{id}', $prefix . 'AdsController@blockAd')->name('block');
    Route::get('/delete-comment/{id}', $prefix . 'AdsController@deleteComment')->name('delete-comment');
});

Route::group(['prefix' => '/users', 'as' => 'users.'], function () use ($prefix) {
    Route::get('/profile/{username}', $prefix . 'UsersController@profile')->name('profile');
    Route::get('/saved', $prefix . 'UsersController@saved')->name('saved');
    Route::post('/update', $prefix . 'UsersController@update')->name('update');
    Route::post('/change-password', $prefix . 'UsersController@changePassword')->name('change-password');
    Route::post('/follow-user', $prefix . 'UsersController@followUser')->name('follow-user');
    Route::post('/user-block/{id}', $prefix . 'UsersController@userBlock')->name('block');
    Route::get('/all', $prefix . 'UsersController@allUsers')->name('all');
});

Route::group(['prefix' => '/auctions', 'as' => 'auctions.'], function () use ($prefix) {
    Route::get('/', $prefix . 'AuctionsController@index')->name('index');
});

Route::group(['prefix' => '/general', 'as' => 'general.'], function () use ($prefix) {
    Route::post('/store-message', $prefix . 'GeneralController@storeMessage')->name('store-message');
    Route::post('/store-report-ad', $prefix . 'GeneralController@storeReportAd')->name('store-report-ad');
    Route::post('/store-rating', $prefix . 'GeneralController@storeRating')->name('store-rating');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('test', 'TestController');
Route::post('/api/sub_categories', 'Api\\CategoriesController@selectSubCategorie')->name('api.sub_categories');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/foo', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('storage:link');
    // Artisan::call('voyager:install');
    return "<h1> OK :) </h1>";
});

Route::get('/tmail', function () {
    $user = User::find(18);
    Mail::to($user)->send(new NewUserNotification($user));
});

app/Http/Controllers/FrontendController/FrontendController.php
<?php

namespace App\Http\Controllers\FrontendController;

use App\Http\Controllers\Controller;
use App\MainCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FrontendController extends Controller
{
    public function index()
    {
        $categories = MainCategory::with('sub_categories')->get();
        return view('frontend.pages.index', compact('categories'));
    }

    public function signup()
    {
        if (!Auth::check()) {
            return view('frontend.pages.signup');
        }
        else{
            return redirect()->to('/');
        }
    }

    public function AboutAs()
    {
        return view('frontend.pages.about-as');
    }

    public function Privacy()
    {
        return view('frontend.pages.privacy');
    }
}

resources/views/frontend/components/ad-sug.blade.php
    @foreach ($ads as $ad)
        <div class="col-md-3 col-sm-6 col-xs-12">
            <a href="{{ route('ad.show-ad' , [$ad->slug]) }}">
            <li class="cards__item">
                <div class="card">
                    <div class="card__image" style="background-image: url({{ $ad->link_images[0]->download_link }})"></div>
                    <div class="card__content">
                        <div class="card__title">
                            <a href="{{ route('ad.show-ad' , [$ad->slug]) }}">
                                {{ $ad->title }}
                            </a>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-map-marker i-color-red"></i> 
                                        <span>{{ $ad->city->name }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-8">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-list i-color-blue"></i>
                                        <span> {{ $ad->sub_category->name }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-clock-o i-color-green"></i>    
                                        <span>{{ $ad->created_at->locale('ar')->diffForHumans() }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            </a>
        </div>
    @endforeach

resources/views/frontend/components/ad.blade.php
@foreach ($ads as $ad)
<div class="col-md-12">
    <div class="contant-ad">
        <div class="ad-image">
            <div style="background-image: url({{ $ad->link_images[0]->download_link }});"></div>
        </div>
        <div class="article-text">
            <h2> <a href="{{ route('ad.show-ad' , [$ad->slug]) }}">{{ $ad->title }} <strong>({{ $ad->price . $ad->currency->icon}})</strong> </a> </h2>
            <div class="s-icon">
                <div class="v-center"> 
                    <i class="fa fa-clock-o i-color-green"></i>    
                    <span>{{ $ad->created_at->locale('ar')->diffForHumans() }}</span>
                </div>
            </div>
            <p> 
                {{-- @if (mb_strlen($ad->description) > 130)
                    {{  mb_substr($ad->description ,0,130,'utf-8') }} ...
                    <a href="#"> قراءة المزيد </a>
                @else
                    {{ $ad->description }}
                @endif --}}
                @foreach ($ad->selected_ad_values as $item)
                    <div class="s-icon">
                        <div class="v-center"> 
                            <span> 
                                <strong>
                                    {{ $item->ad_attribute->attribute_group->name }}:
                                </strong>
                                {{ $item->attribute->value }}
                            </span>
                        </div>
                    </div>
                @endforeach
                @foreach ($ad->input_ad_values as $item)
                    @if (isset($item->unit->name) and $item->unit->name != 'مزايا إضافية')            
                        <div class="s-icon">
                            <div class="v-center"> 
                                <span> 
                                    <strong>
                                        {{ $item->ad_attribute->attribute_group->name }}:
                                    </strong>
                                    {{ $item->value }}/{{ $item->unit->name??'' }}
                                </span>
                            </div>
                        </div>
                    @endif
                @endforeach
            </p>
            <div class="">

                <div class="s-icon">
                    <div class="v-center"> 
                        <i class="fa fa-map-marker i-color-red"></i> 
                        <span>{{ $ad->city->name }}</span>
                    </div>
                </div>

                <div class="s-icon">
                    <div class="v-center"> 
                        <i class="fa fa-list i-color-blue"></i>
                        <span> {{ $ad->sub_category->name }}</span>
                    </div>
                </div>

                <div class="s-icon">
                    <div class="v-center"> 
                        <i class="fa fa-clock-o i-color-green"></i>    
                        <span> {{ date('yy-m-d',strtotime($ad->created_at)) }}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="btn-group-sm">

                            <button type="button" class="btn btn-none" onclick="ajaxSavedAd({{$ad->id}})">
                                <i class="fa-18 fa fa-bookmark @if ($ad->saved)  i-color-red @else  i-color-gray @endif" id="saved_icon_{{$ad->id}}" aria-hidden="true"></i>
                            </button>
                            <button type="button" class="btn btn-out-red btn-sm" id="open-report-ad" data-toggle="modal" data-target="#reportModel" data-title-ad="{{ $ad->title }}" data-id-ad="{{ $ad->id }}">
                                <i class="fa fa-envelope-o" aria-hidden="true"></i>
                                أبلغنا عن اساءة
                            </button>
                        </div>

                    </div>
                </div>
                  
            </div>
        </div>
        <div class="user-image">
            <img class="img-circle avatar img-thumbnail" height="70px"  width="70px" src="{{ url('storage/' . $ad->user->avatar) }}">
            <p> <a href="{{ route('users.profile' , $ad->user->username ?? 'null') }}"> {{$ad->user->name}} </a></p>
        </div>
        <div class="ad-active @if ($ad->status == Helper::ACTIVE) on @elseif ($ad->status == Helper::DEACTIVE) off @endif">
            <i class="fa @if ($ad->status == Helper::ACTIVE) fa-eye @elseif ($ad->status == Helper::DEACTIVE) fa-eye-slash @endif" aria-hidden="true"></i>
            @if ($ad->status == Helper::ACTIVE)
                <span>مفتوح</span>    
            @elseif ($ad->status == Helper::DEACTIVE) 
                <span>مفلق</span>
            @endif
        </div>
    </div>
</div>

@include('frontend.components.model-report')
@endforeach

@push('scripts')
    
<script>
    function ajaxSavedAd (id){
        jQuery.ajax({
            url: "{{ route('ad.addToSaved') }}",
            method: 'post',
            data: {
                _token: "{{csrf_token()}}",
                ad_id: id,
            },
            success: function(result){
                console.log(result);
                if(result.success == true){
                    toastr.success(result.message);
                    if(result.action == 'saved'){
                        
                        $("#saved_icon_" + id).removeClass('i-color-gray');
                        $("#saved_icon_" + id).addClass('i-color-red');
                    }
                    if(result.action == 'unsaved'){
                        $("#saved_icon_" + id).removeClass('i-color-red');
                        $("#saved_icon_" + id).addClass('i-color-gray');
                    }
                }
                else{
                    toastr.error(result.message)
                }

            }
        });
    }
</script>
@endpush

resources/views/frontend/components/auction.blade.php
<div class="row">
    @foreach ($auctions as $auction)
        <div class="col-md-4 col-sm-6 col-xs-12">
            <a href="{{ route('ad.show-ad' , [$auction->ad->slug]) }}">
            <li class="cards__item">
                <div class="card">
                    <div class="card__image" style="background-image: url({{ $auction->ad->link_images[0]->download_link }})"></div>
                    <div class="card__content">
                        <div class="timer text-center" style="position: absolute;">
                            <ul>
                                <li><span id="days{{ $auction->id }}"></span>يوم</li>
                                <li><span id="hours{{ $auction->id }}"></span>ساعة</li>
                                <li><span id="minutes{{ $auction->id }}"></span>دقيقة</li>
                                <li><span id="seconds{{ $auction->id }}"></span>ثواني</li>
                            </ul>
                        </div>
                        <div class="card__title">
                            <a href="{{ route('ad.show-ad' , [$auction->ad->slug]) }}">
                                {{ $auction->ad->title }}
                            </a>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-map-marker i-color-red"></i> 
                                        <span>{{ $auction->ad->city->name }}</span>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-8">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-list i-color-blue"></i>
                                        <span> {{ $auction->ad->sub_category->name }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="s-icon" style="margin-left: 0px;">
                                    <div class="v-center"> 
                                        <i class="fa fa-clock-o i-color-green"></i>    
                                        <span>{{ $auction->created_at->locale('ar')->diffForHumans() }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            </a>
        </div>
    @endforeach
</div>
@push('scripts')
    <script src="{{ asset('js/app-all.js') }}"></script>
    <script>
        $( document ).ready(function() {
            let json = ("{{ json_encode( $timer) }}").replace(/&quot;/g,'"');
            var data = JSON.parse(json);
            data.forEach((value, index) => {
                timer(value.id , value.start_date , value.end_date)
            })
        });
    </script>
@endpush

resources/views/frontend/components/category.blade.php
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    <div class="e-panel panel-green">
        <div class="card-panel-heading">
            <img src="{{url('storage/' . $category->icon)}}" height="27px" alt="">
            {{$category->name}}
            <span class="see-all">
            <a href="#"> عرض الجميع </a>
            </span>
        </div>
        <div class="panel-body static-body">
            @foreach ($category->sub_categories as $item)
            <a  class="sub-cat-link inline" href="{{ route('ad.show-ads' , ['sub_category_id' => $item->id , 'main_category_id' => $category->id]) }}">
                <span>
                    {{$item->name}}
                </span>                
            </a>
            @endforeach
        </div>
    </div>
</div>

resources/views/frontend/components/login-model.blade.php
    <!-- Authentication Links -->
@guest
    <li>
        <a href="#" data-toggle="modal" data-target="#loginModel">
            <i class="fa fa-sign-in" aria-hidden="true"></i>
            تسجيل دخول
        </a>
    </li>

    @if (Route::has('register'))
        <li>
            <a href="{{ route('frontend.signup') }}">
                <i class="fa fa-user-plus" aria-hidden="true"></i>
                حساب جديد
            </a>
        </li>
    @endif
@else
    <li class="dropdown">
        <a id="navbarDropdown" class="dropbtn" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
           <i class="fa fa-user" aria-hidden="true"></i>
            {{ Auth::user()->name }} <span class="caret"></span>
        </a>

        <ul class="dropdown-content text-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{{ route('logout') }}" 
                onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                {{ __('تسجيل الخروج') }}
            </a>
            <a class="dropdown-item" href="{{ route('users.profile' , [Auth::user()->username ?? 'null']) }}" >
                <i class="fa fa-user" aria-hidden="true"></i>
                الصفحة الشخصية
            </a>
            <a class="dropdown-item" href="/admin" >
                <i class="fa fa-user" aria-hidden="true"></i>
                لوحة التحكم
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                @csrf
            </form>
        </ul>
    </li>
@endguest
<div id="loginModel" class="modal fade text-center" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div id="content">
                    <div class="header-login">
                        <h2>
                            <i class="fa fa-sign-in" aria-hidden="true"></i>
                            تسجيل الدخول 
                        </h2>
                    </div>
                    <form method="POST" action="{{ route('login') }}">
                        @csrf
                        <div class="form_section">
                            <div class="form-group">
                                <input type="text" class="e-form-control" name="email" id="email" placeholder="ادخل البريد الالكتروني" required=""> 
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span> 
                                @enderror
                            </div>
                            <div class="form-group">
                                <input id="password" type="password" class="e-form-control @error('password') is-invalid @enderror" placeholder="كلمة المرور" name="password" required autocomplete="current-password"> 
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span> 
                                @enderror
                            </div>
                            <button type="submit" class="btn btn-red">تسجيل دخول</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/frontend/components/service.blade.php
@push('scripts')

    <script src="{{ asset('js/sweet-confirm.js') }}"></script>

@endpush

@if ($errors->any())
    @foreach ($errors->all() as $error)
        @php
            toastr()->error($error);
        @endphp
    @endforeach
@endif

@if(Session::has('success'))
    @php
        toastr()->success(Session::get('success'));
    @endphp
@endif

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>صورة</th>
                <th>العنوان</th>
                <th class="text-center">الوقت</th>
                <th class="text-center">العروض</th>
                @if ($action == true)
                    <th class="text-center">خيارات</th>
                @else
                    <th class="text-center">الناشر</th>
                @endif
                <th class="text-center">حفظ</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($services as $service)
                @php
                    $url = route('services.show' , [$service->slug]) ;
                @endphp
                <tr>
                    <td scope="row">
                        <img class="avatar img-thumbnail"   src="{{ $service->user->link_image ?? '' }}" width="60px" height="60px">
                    </td>
                    <td onclick="window.location='{{$url}}'" class="cursor-pointer">
                        <a style="font-size: 16px" href="{{ $url }}">{{ $service->title }}</a>
                        <p style="padding: 0px; margin: 4px 0px;">
                            @if (mb_strlen($service->description) > 50)
                                {{  mb_substr($service->description ,0,50,'utf-8') }} ...
                                <a href="{{ $url }}"> قراءة المزيد </a>
                            @else
                                {{ $service->description }}
                            @endif
                        </p>

                        <div class="s-icon">
                            <div class="v-center"> 
                                <i class="fa fa-map-marker i-color-pinck"></i> 
                                <span>{{ $service->city->name }}</span>
                            </div>
                        </div>

                        <div class="s-icon">
                            <div class="v-center"> 
                                <i class="fa fa-list-alt i-color-blue"></i>
                                <span> {{ $service->sub_category->name }}</span>
                            </div>
                        </div>

                        <div class="s-icon">
                            <div class="v-center"> 
                                <i class="fa fa-clock-o i-color-green"></i>    
                                <span> {{ date('yy-m-d',strtotime($service->created_at)) }}</span>
                            </div>
                        </div>
                            
                    </td>

                    <td class="text-center"> {{ $service->created_at->locale('ar')->diffForHumans() }} </td>
                    <td class="text-center">{{ $service->offers->count() }}</td>
                    @if (Auth::id() == $service->user_id and $action == true)
                    <td>
                        {{-- <div class="btn-group" role="group" > --}}
                            <button type="button" onclick="confirmForm('removeService_{{$service->id}}')" class="btn btn-danger btn-xs" style="margin: 2px;">
                                <i class="fa fa-times" aria-hidden="true"></i>
                                حذف
                            </button>
                            <a href="{{ route('voyager.services.edit' , $service) }}" target="_blank" class="btn btn-info btn-xs" style="margin: 2px;">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>                            
                                تعديل
                            </a>
                        {{-- </div> --}}
                        <form action="{{ route('services.destroy' , [$service->id]) }}" method="POST" id="removeService_{{$service->id}}">
                            @csrf
                        </form>
                    </td>
                    @else
                    <td class="text-center">{{ $service->user->name ?? '' }}</td>
                    @endif
                    <td class="text-center">
                        <button type="button" class="btn btn-none" onclick="ajaxSavedService({{$service->id}})">
                            <i class="fa-18 fa fa-bookmark @if ($service->saved)  i-color-red @else  i-color-gray @endif" id="saved_icon_{{$service->id}}" aria-hidden="true"></i>
                        </button>
                    </td>
                </tr>
                @endforeach
            </tbody>
    </table>
</div>
@push('scripts')
    
<script>
    function ajaxSavedService (id){
        jQuery.ajax({
            url: "{{ route('services.addToSaved') }}",
            method: 'post',
            data: {
                _token: "{{csrf_token()}}",
                service_id: id,
            },
            success: function(result){
                console.log(result);
                if(result.success == true){
                    toastr.success(result.message);
                    if(result.action == 'saved'){
                        
                        $("#saved_icon_" + id).removeClass('i-color-gray');
                        $("#saved_icon_" + id).addClass('i-color-red');
                    }
                    if(result.action == 'unsaved'){
                        $("#saved_icon_" + id).removeClass('i-color-red');
                        $("#saved_icon_" + id).addClass('i-color-gray');
                    }
                }
                else{
                    toastr.error(result.message)
                }

            }
        });
    }
</script>
@endpush

resources/views/frontend/components/users.blade.php
@push('scripts')

    <script src="{{ asset('js/sweet-confirm.js') }}"></script>

@endpush

@if ($errors->any())
    @foreach ($errors->all() as $error)
        @php
            toastr()->error($error);
        @endphp
    @endforeach
@endif

@if(Session::has('success'))
    @php
        toastr()->success(Session::get('success'));
    @endphp
@endif

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th>صورة</th>
                <th>الاسم</th>
                <th class="text-center">عدد الاعلانات</th>
                <th class="text-center">عدد الخدمات</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($users as $user)
                @php
                    $url = route('users.profile' , [$user->username ?? 'null']) ;
                @endphp
                <tr>
                    <td scope="row">
                        <img class="avatar img-circle img-thumbnail"   src="{{ $user->link_image ?? '' }}" width="60px" height="60px">
                    </td>
                    <td onclick="window.location='{{$url}}'" class="cursor-pointer">
                        <a style="font-size: 16px" href="{{ $url }}">{{ $user->name }}</a>
                        <p style="padding: 0px; margin: 4px 0px;">
                            @if (mb_strlen($user->bio) > 50)
                                {{  mb_substr($user->bio ,0,50,'utf-8') }} ...
                                <a href="{{ $url }}"> قراءة المزيد </a>
                            @else
                                {{ $user->bio }}
                            @endif
                        </p>

                        <div class="s-icon">
                            <div class="v-center"> 
                                <i class="fa fa-map-marker i-color-pinck"></i> 
                                <span>{{ $user->city->name ?? "" }}</span>
                            </div>
                        </div>

                        <div class="s-icon">
                            <div class="v-center"> 
                                <i class="fa fa-clock-o i-color-green"></i>    
                                <span>تم الانضمام منذ {{ $user->created_at->locale('ar')->diffForHumans() }}</span>
                                
                            </div>
                        </div>
                            
                    </td>

                    <td class="text-center">
                        {{ $user->ads->count() }}
                    </td>
                    <td class="text-center">
                        {{ $user->services->count() }}
                    </td>
                </tr>
                @endforeach
            </tbody>
    </table>
</div>
@push('scripts')
    
<script>
    function ajaxSavedService (id){
        jQuery.ajax({
            url: "{{ route('services.addToSaved') }}",
            method: 'post',
            data: {
                _token: "{{csrf_token()}}",
                service_id: id,
            },
            success: function(result){
                console.log(result);
                if(result.success == true){
                    toastr.success(result.message);
                    if(result.action == 'saved'){
                        
                        $("#saved_icon_" + id).removeClass('i-color-gray');
                        $("#saved_icon_" + id).addClass('i-color-red');
                    }
                    if(result.action == 'unsaved'){
                        $("#saved_icon_" + id).removeClass('i-color-red');
                        $("#saved_icon_" + id).addClass('i-color-gray');
                    }
                }
                else{
                    toastr.error(result.message)
                }

            }
        });
    }
</script>
@endpush