routes/web.php
<?php

use App\Mail\NewUserNotification;
use App\MainCategory;
use App\SubCategory;
use App\User;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;
use TCG\Voyager\Facades\Voyager;

$prefix = 'FrontendController\\';

Route::group(['prefix' => '/', 'as' => 'frontend.'], function () use ($prefix) {
    Route::get('/', $prefix . 'FrontendController@index')->name('index');
    Route::get('/signup', $prefix . 'FrontendController@signup')->name('signup');
    Route::get('/about-as', $prefix . 'FrontendController@AboutAs')->name('about-as');
    Route::get('/privacy', $prefix . 'FrontendController@Privacy')->name('privacy');
});

Route::group(['prefix' => '/services', 'as' => 'services.'], function () use ($prefix) {
    Route::get('/', $prefix . 'ServicesController@index')->name('index');
    Route::get('/create', $prefix . 'ServicesController@create')->name('create');
    Route::post('/store', $prefix . 'ServicesController@store')->name('store');
    Route::get('/show/{slug}', $prefix . 'ServicesController@show')->name('show');
    Route::get('/review/{slug}', $prefix . 'ServicesController@review')->name('review');
    Route::post('/set-offer', $prefix . 'ServicesController@setOffer')->name('set_offer');
    Route::post('/destroy/{id}', $prefix . 'ServicesController@destroy')->name('destroy');
    Route::post('/add-to-saved', $prefix . 'ServicesController@addToSaved')->name('addToSaved');
    Route::post('/block/{id}', $prefix . 'ServicesController@blockService')->name('block');
});

Route::group(['prefix' => '/ads', 'as' => 'ad.'], function () use ($prefix) {
    Route::get('/create', $prefix . 'AdsController@createAd')->name('create');
    Route::post('/generate-template', $prefix . 'AdsController@generateTemplate')->name('template');
    Route::post('/store', $prefix . 'AdsController@store')->name('store');
    Route::get('/', $prefix . 'AdsController@showAds')->name('show-ads');
    Route::get('/category/{id}', $prefix . 'AdsController@getAdsWhereCategory')->name('category');
    Route::get('/show/{id}', $prefix . 'AdsController@showAd')->name('show-ad');
    Route::post('/add-to-saved', $prefix . 'AdsController@addToSaved')->name('addToSaved');
    Route::post('/set-auction-offer', $prefix . 'AdsController@setAuctionOffer')->name('set-auction-offer');
    Route::post('/set-comment', $prefix . 'AdsController@setComment')->name('set-comment');
    Route::post('/block/{id}', $prefix . 'AdsController@blockAd')->name('block');
    Route::get('/delete-comment/{id}', $prefix . 'AdsController@deleteComment')->name('delete-comment');
});

Route::group(['prefix' => '/users', 'as' => 'users.'], function () use ($prefix) {
    Route::get('/profile/{username}', $prefix . 'UsersController@profile')->name('profile');
    Route::get('/saved', $prefix . 'UsersController@saved')->name('saved');
    Route::post('/update', $prefix . 'UsersController@update')->name('update');
    Route::post('/change-password', $prefix . 'UsersController@changePassword')->name('change-password');
    Route::post('/follow-user', $prefix . 'UsersController@followUser')->name('follow-user');
    Route::post('/user-block/{id}', $prefix . 'UsersController@userBlock')->name('block');
    Route::get('/all', $prefix . 'UsersController@allUsers')->name('all');
});

Route::group(['prefix' => '/auctions', 'as' => 'auctions.'], function () use ($prefix) {
    Route::get('/', $prefix . 'AuctionsController@index')->name('index');
});

Route::group(['prefix' => '/general', 'as' => 'general.'], function () use ($prefix) {
    Route::post('/store-message', $prefix . 'GeneralController@storeMessage')->name('store-message');
    Route::post('/store-report-ad', $prefix . 'GeneralController@storeReportAd')->name('store-report-ad');
    Route::post('/store-rating', $prefix . 'GeneralController@storeRating')->name('store-rating');
});

Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('test', 'TestController');
Route::post('/api/sub_categories', 'Api\\CategoriesController@selectSubCategorie')->name('api.sub_categories');

Route::get('/redirect', 'SocialAuthFacebookController@redirect');
Route::get('/callback', 'SocialAuthFacebookController@callback');

Route::get('/foo', function () {
    Artisan::call('config:cache');
    Artisan::call('cache:clear');
    Artisan::call('storage:link');
    // Artisan::call('voyager:install');
    return "<h1> OK :) </h1>";
});

Route::get('/tmail', function () {
    $user = User::find(18);
    Mail::to($user)->send(new NewUserNotification($user));
});

app/User.php
<?php

namespace App;

use App\Providers\Helper;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class User extends \TCG\Voyager\Models\User implements MustVerifyEmail
{
    use Notifiable;
    protected $appends = ['link_image', 'following', 'rate'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'avatar', 'bio', 'city_id', 'phone'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function services()
    {
        return $this->hasMany(Service::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function offers()
    {
        return $this->hasMany(Offer::class);
    }

    public function ads()
    {
        return $this->hasMany(Ad::class);
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function scopeFindByUsername($query, $username)
    {
        return $query->where('username', '=', $username);
    }

    public function getLinkImageAttribute()
    {
        if ($this->avatar) {
            return str_replace('\\', '/', url(Storage::url($this->avatar)));
        }
    }


    public function saved_services()
    {
        return $this->belongsToMany(
            Service::class,
            'saved_services',
            'user_id',
            'service_id'
        );
    }

    public function saved_ads()
    {
        return $this->belongsToMany(
            Ad::class,
            'saved_ads',
            'user_id',
            'ad_id'
        );
    }
    public function getFollowingAttribute()
    {
        if (!Auth::check()) {
            return 0;
        } else {
            $follow_user = Follower::where('user_id', Auth::id())
                ->where('following_id', $this->id)->first();
            return ($follow_user) ? 1 : 0;
        }
    }

    public function getRateAttribute()
    {
        $rate = Rating::where('user_id', '=', $this->id);
        $count = $rate->count();
        if ($count == 0) {
            return 0;
        }
        $sum = $rate->sum('value');
        return round(($sum / (5 * $count)) * 5, 1);
    }

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($user) {
            $user->username = Helper::Slugify($user->name . ' ' . Str::random(4));
        });
    }

    public function city()
    {
        return $this->belongsTo(City::class, 'city_id');
    }
}

app/Http/Controllers/FrontendController/UsersController.php
<?php

namespace App\Http\Controllers\FrontendController;

use App\Follower;
use App\Http\Controllers\ContentTypes\Image as ContentImage;
use App\Http\Controllers\Controller;
use App\Mail\UserBlockNotification;
use App\Providers\Helper;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except(['profile', 'followUser']);
    }

    public function profile($username)
    {
        $user = User::findByUsername($username)->first();
        if ($user) {
            $countAds = 0;
            $countServices = 0;
            if (Auth::id() == $user->id) {
                $services = $user->services()->orderBy('created_at', 'DESC')->paginate(7);;
                $ads = $user->ads()->orderBy('created_at', 'DESC')->paginate(7);
                $countAds = $user->ads->count();
                $countServices = $user->services->count();
            } else {
                $services = $user->services()->whereStatus(Helper::ACTIVE)->orderBy('created_at', 'DESC')->paginate(7);;
                $ads = $user->ads()->whereStatus(Helper::ACTIVE)->orderBy('created_at', 'DESC')->paginate(7);
                $countAds = $user->ads->count();
                $countServices = $user->services->count();
            }
            return view('frontend.pages.users.profile', compact(
                'user',
                'services',
                'ads',
                'countServices',
                'countAds'
            ));
        }
        return view('frontend.pages.404');
    }

    public function saved()
    {
        $services = Auth::user()->saved_services()->whereStatus(Helper::ACTIVE)->orderBy('created_at', 'DESC')->paginate(7);
        $ads = Auth::user()->saved_ads()->whereStatus(Helper::ACTIVE)->orderBy('created_at', 'DESC')->paginate(7);
        return view('frontend.pages.users.saved', compact('services', 'ads'));
    }

    public function update(Request $request)
    {
        // return $request;
        $validatedData = $this->validate($request, $this->rule(Auth::id()), [], $this->niceNames());
        if ($request->hasFile('img_avatar')) {
            $request['avatar'] = (new ContentImage($request, 'users', 'img_avatar'))->handle();
        }
        // return $request;
        Auth::user()->update($request->all());
        // return $path;
        toastr()->success('تم تحديث بياناتك بنجاح');
        return redirect()->back();
    }

    public function changePassword(Request $request)
    {

        $this->validate($request, [
            'current-password' => 'required',
            'password' => 'required|same:password|min:6',
            'password_confirmation' => 'required|same:password',
        ]);

        $current_password = Auth::User()->password;
        if (Hash::check($request->input('current-password'), $current_password)) {
            $user_id = Auth::User()->id;
            $obj_user = User::find($user_id);
            $obj_user->password = Hash::make($request->input('password'));;
            $obj_user->save();
            toastr()->success('تم تغيير كلمة المرور بنجاح');
            return redirect()->back();
        } else {
            // toastr()->error('كلمة المرور الحالية خاطئة') ;   
            return redirect()->back()->withErrors('كلمة المرور الحالية خاطئة');
        }
    }

    protected function rule($id)
    {
        return  [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', "unique:users,email,$id,id"],
            'bio' => ['string', 'max:1000'],
            'avatar' => ['mimes:jpeg,jpg,png,gif', 'max:10000']
        ];
    }

    public function niceNames()
    {
        return [
            'name' => __('fillable.name'),
            'email' => __('fillable.email'),
            'bio' => __('fillable.bio'),
            'avatar' => __('fillable.avatar'),
        ];
    }


    public function followUser(Request $request)
    {
        if (isset($request->following_id) and Auth::check()) {
            $follow_user = Follower::where('user_id', Auth::id())
                ->where('following_id', $request->following_id)->first();

            if ($follow_user) {
                $follow_user->delete();
                return response()->json([
                    'success' => true,
                    'message' => 'تم الغاء المتابعة',
                    'action' => 'unsaved'
                ]);
            } else {
                Follower::insert([
                    'following_id' => $request->following_id,
                    'user_id' => Auth::id()
                ]);
                return response()->json([
                    'success' => true,
                    'message' => "تم المتابعة بنجاح",
                    'action' => 'saved'
                ]);
            }
        }
        return response()->json([
            'success' => false,
            'message' => "يجب تسجيل الدخول اولا"
        ]);
    }

    public function userBlock($id)
    {

        $user = user::findOrFail($id);
        $user->status = ($user->status == Helper::ACTIVE) ?  Helper::DEACTIVE : Helper::ACTIVE;
        $user->save();
        if ($user->status == Helper::DEACTIVE) {
            Mail::to($user)->send(new UserBlockNotification($user));
            return redirect()->back()->with([
                'message'    => 'The block was successful',
                'alert-type' => 'success',
                ]);
            }
            return redirect()->back()->with([
            'message'    => 'The request was successfully accepted',
            'alert-type' => 'success',
        ]);
    }

    public function allUsers(Request $request)
    {
        // return $request;
        $users = User::select('*');
        
        if ($request->s != null) {
            $users->where('name', 'LIKE', "%$request->s%")
                ->orWhere('bio', 'LIKE', "%$request->s%")
                ->orWhere('email', 'LIKE', "%$request->s%")
                ->orWhere('username', 'LIKE', "%$request->s%");
        }
        if ($request->city_id != null) {
            $users->where('city_id', '=', $request->city_id);
        }
        if (!isset($request->order_by) or $request->order_by == null) {
            $users->orderBy('created_at', 'DESC');
        }

        if ($request->order_by != null) {
            $users->orderBy('created_at', $request->order_by);
        }

        $data  =  $users->paginate(7)->setPath('')->appends($request->all());
        return view('frontend.pages.users.all', ['users' => $data]);
    }

}

resources/views/frontend/pages/users/all.blade.php
@extends('frontend.layouts.master')

@push('title')
    المحفوظات
@endpush

@section('content')
<div class="container-fluid color-gray">
    <div class="container">
        <div class="row text-center font-kufi">
            <br>
            <h2>
                <i class="fa fa-users i-color-red" aria-hidden="true"></i>
                 قائمة مستخدمي النظام 
            </h2>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="row">
                        <form action="{{ route('users.all') }}" method="GET">
                            @include('frontend.forms.select' , [
                                'name' => 'city_id',
                                'label' => 'المدينة',
                                'required' => false,
                                'options' => Helper::getCities(),
                                'col' => 4,
                            ])
                            <div class="form-group col-sm-12 col-md-8">

                                <label class="text-right" for=""> 
                                    ابحث: 
                                </label>
                                <div class="input-group">
                                    <input type="text" class="e-form-control" name="s" value="{{ Request::get('s') }}" placeholder="اسم المستخدم او البريد الالكتروني ...">
                                    <div class="input-group-btn">
                                        <button class="btn btn-red" type="submit">
                                            <i class="fa fa-search" aria-hidden="true"></i>
                                            بحث
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="container">
        <div class="row" id="">
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
                <div class="e-panel panel-default">
                    <div class="panel-body">                        
                        <div class="row">
                            <div class="col-md-12">
                                @include('frontend.components.users' , ['users' => $users])
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-md-12 text-center">
                                {{ $users->links() }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/frontend/pages/users/profile.blade.php
@extends('frontend.layouts.master')

@push('title')
    {{$user->name}}
@endpush

@section('content')

<div class="container-fluid color-gray">
    <div class="row "> 
        <br>
        <div class="user-cover text-center v-center">
            <div class="user-information">
                <img class="img-circle avatar img-thumbnail"   src="{{ url('storage/' . $user->avatar) }}" width="115px" height="115px">
                <div class="shop-details">
                    <h3>{{ $user->name }}</h3>
                    <div style="margin-bottom: 8px">
                        <button type="button" class="btn btn-sm @if ($user->following) btn-red @else btn-success @endif" id="btn_follow" onclick="ajaxFollowingUser({{$user->id}})">
                            <i class="fa @if ($user->following) fa-check @else fa-plus @endif" aria-hidden="true" id="icon_following"></i>
                            <span id="text_following">
                                @if($user->following) متابَع @else تابعني @endif
                            </span>
                        </button>
                        @if (Auth::check())
                            @if (Auth::user()->id != $user->id)
                            <button type="button" class="btn btn-sm btn-success" data-toggle="modal" data-target="#ratingModel" >
                                <i class="fa fa-comment-o" aria-hidden="true"></i>
                                <span>
                                    اضف تقييم
                                </span>
                            </button>
                            @endif
                        @endif
                    </div>
                    <span> 
                        <i class="fa fa-shield" aria-hidden="true"></i>
                         حساب موثق 
                    </span>
                    <span>.</span>
                    <span> 
                        <i class="fa fa-clock-o" aria-hidden="true"></i>
                        تم الانضمام:  {{ $user->created_at->locale('ar')->diffForHumans() }}
                    </span>
                    <span>.</span>
                    <span> 
                        <i class="fa fa-location-arrow" aria-hidden="true"></i>
                        {{ $user->city->name ?? '' }}
                    </span>
                    <div class="col-md-12">
                        <div class="content-rate v-center">
                            <div style="margin-bottom: 6px;font-size: 16px;padding-left: 10px;">
                                <strong> ({{ $user->rate }}) </strong>
                            </div>
                            @include('frontend.forms.rate' , ['name' => 'rate' , 'check' => true ,'value' => $user->rate])
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="nav-tab color-fff">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <ul class="nav nav-pills">
                            <li class="active"><a data-toggle="pill" href="#menu2">
                                <i class="fa fa-bullhorn" aria-hidden="true"></i>
                                الاعلانات
                            </a></li>
                            <li class=""><a data-toggle="pill" href="#menu3">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                الطلبات
                            </a></li>
                            <li class=""><a data-toggle="pill" href="#user-info">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                المعلومات الشخصية
                            </a></li>
                            @if (Auth::check() and Auth::user()->username == $user->username)
                                <li class=""><a data-toggle="pill" href="#menu4">
                                    <i class="fa fa-cog" aria-hidden="true"></i>
                                    الاعدادات
                                </a></li>
                                <li class=""><a data-toggle="pill" href="#change-password">
                                    <i class="fa fa-key" aria-hidden="true"></i>    
                                    تغيير كلمة المرور
                                </a></li>
                            @endif
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br/>
    <div class="container">
        <div class="row" id="">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="e-panel panel-default">
                    <div class="panel-body">
                        <div class="tab-content">
                            <div id="user-info"  class="tab-pane fade">
                                <div class="row">
                                    <div class="col-md-12">
                                        <h3>نبذة عني</h3>
                                        <p> {!! nl2br($user->bio) !!} </p>
                                    </div>
                                </div>
                            </div>
                            <div id="menu2"  class="tab-pane fade  in active">
                                <div class="row">
                                    @if ($ads->count() == 0)
                                        <div class="col-md-12 text-center">
                                            <p> لا توجد نتائج 😉 </p>
                                            <a href="{{ route('ad.create') }}" class="btn btn-red"> 
                                                <i class="fa fa-plus-circle" aria-hidden="true"></i> 
                                                قم باضافة اعلان مجانا
                                            </a>
                                        </div>
                                    @endif                                
                                    <div class="col-md-12">
                                        @include('frontend.components.ad' , compact('ads'))
                                    </div>
                                </div>
                                <div class="row text-center">
                                    {{ $ads->links() }}
                                </div>
                            </div>

                            <div id="menu3"  class="tab-pane fade">
                                <div class="row">
                                    @if ($services->count() == 0)
                                        <div class="col-md-12 text-center">
                                            <p> لا توجد نتائج 😉 </p>
                                            <a href="{{ route('services.create') }}" class="btn btn-red"> 
                                                <i class="fa fa-plus-circle" aria-hidden="true"></i> 
                                                قم باضافة طلبك مجانا
                                            </a>
                                        </div>
                                    @else
                                        <div class="col-md-12">
                                            @include('frontend.components.service' , ['services' => $services ,  'action' => true])
                                        </div>
                                    @endif
                                    <div class="row">
                                        <div class="col-md-12 text-center">
                                            {{ $services->links() }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @if (Auth::check() and Auth::user()->username == $user->username)
                                <div id="menu4"  class="tab-pane fade">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <h4>تعديل المعلومات الشخصية</h4>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <form action="{{ route('users.update') }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            @include('frontend.forms.user')
                                        </form>
                                    </div>     
                                </div>
                                <div id="change-password"  class="tab-pane fade">
                                    <div class="row">
                                        <form action="{{ route('users.change-password') }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            @include('frontend.forms.password')
                                        </form>
                                    </div>
                                </div>
                            @endif
                                
                        </div>
                    </div>
                </div>
            </div>
        
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <div class="e-panel panel-default">
                    <div class="e-panel-heading">
                        <a class="btn-collapse pull-left" data-toggle="collapse" href="#user-info-num" aria-expanded="true">
                            <i class="fa fa-angle-right"></i>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        احصائيات
                    </div>
                    <div id="user-info-num" class="panel-collapse collapse collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table table-borderless" style="margin-bottom: 0px;">
                                        <tbody>
                                            <tr>
                                                <th style="width: 115px;">عدد الاعلانات:</th>
                                                <td> {{ $countServices }}</td>
                                            </tr>
                                            <tr>
                                                <th style="width: 115px;">عدد الطلبات:</th>
                                                <td>{{ $countAds }}</td>
                                            </tr>
                                            <tr>
                                                <th style="width: 115px;">المتابعين:</th>
                                                <td>{{ Helper::CountFollowers($user->id) }}</td>
                                            </tr>
                                            <tr>
                                                <th style="width: 115px;">المتابعون:</th>
                                                <td>{{ Helper::CountFollowing($user->id) }}</td>
                                            </tr>
                                            <tr>
                                                <th style="width: 115px;">تاريخ الانضمام:</th>
                                                <td>{{ $user->created_at->locale('ar')->toFormattedDateString() }}</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@include('frontend.components.model-rating')
@endsection

@push('scripts')
    
<script>
    function ajaxFollowingUser (id){
        jQuery.ajax({
            url: "{{ route('users.follow-user') }}",
            method: 'post',
            data: {
                _token: "{{csrf_token()}}",
                following_id: id,
            },
            success: function(result){
                console.log(result);
                if(result.success == true){
                    toastr.success(result.message);
                    if(result.action == 'saved'){
                        $("#btn_follow").removeClass('btn-success');
                        $("#btn_follow").addClass('btn-red');
                        
                        $("#icon_following").removeClass('fa-plus');
                        $("#icon_following").addClass('fa-check');
                        $("#text_following").text('متابَع');
                    }
                    if(result.action == 'unsaved'){
                        $("#btn_follow").removeClass('btn-red');
                        $("#btn_follow").addClass('btn-success');

                        $("#icon_following").removeClass('fa-check');
                        $("#icon_following").addClass('fa-plus');
                        $("#text_following").text('تابعني');
                        
                    }
                }
                else{
                    toastr.error(result.message)
                }

            }
        });
    }
</script>
@endpush